name: docker

instance_groups:
  - name: docker
    instances: 1 
    azs: [z1]
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: docker
        release: docker

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
  - name: docker
    version: latest

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

